version: '3.8'

services:
    flrepository:
        restart: always
        container_name: flrepository
        build: application
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - default
        ports:
            - "9013:9012"
        depends_on:
            - repositorydb
    repositorydb:
        container_name: repositorydb
        restart: always
        build: mongo_db
        networks:
            - default
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    default:
        driver: bridge
        name: custom_fl
