version: '3.8'
services:
  trainingmain:
    restart: always
    image: karola766/trainingcollector:latest
    container_name: trainingmain
    build: application
    networks:
      - default
    extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          memory: 30g
networks:
  default:
    driver: bridge
    name: custom_fl
