version: '3.8'

services:
    flrepository:
        restart: always
        image: karola766/flrepository:latest
        container_name: flrepository
        environment:
            - HOST=0.0.0.0
            - PORT=9012
            - DB_PORT=27017
            - SERVER_PORT=8000
            - DB_ADDRESS=repositorydb
        build:
            context: "."
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - default
        ports:
            - "9013:9012"
        depends_on:
            - repositorydb
    repositorydb:
        image: karola766/repositorydb:latest
        container_name: repositorydb
        restart: always
        build:
            context: "."
            dockerfile: "Dockerfile.db"
        networks:
            - default
        ports:
            - "27017-27019:27017-27019"
        #volumes:
            #- type: bind
            #  source: ./mongo_db/dump
            #  target: /dump
            #- type: bind
            #  source: ./mongo_volume
            #  target: /bitnami/mongodb
        extra_hosts:
            - "host.docker.internal:host-gateway"

