version: '3.8'

services:
    fl_repository:
        restart: always
        container_name: fl_repository
        build: application
        networks:
            - default
        ports:
            - "9013:9012"
        depends_on:
            - repository_db
    repository_db:
        container_name: repository_db
        restart: always
        build: mongo_db
        networks:
            - default

networks:
    default:
        driver: bridge
        name: custom_fl
