version: '3.8'

services:
    flrepository:
        restart: always
        container_name: flrepository
        build:
            context: "."
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - default
        ports:
            - "9013:9012"
        depends_on:
            - repositorydb
    repositorydb:
        container_name: repositorydb
        restart: always
        build:
            context: "."
            dockerfile: "Dockerfile.db"
        networks:
            - default
        volumes:
            - type: bind
              source: ./mongo_db/dump
              target: /dump
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    default:
        driver: bridge
        name: custom_fl
